-- Catalog pictures served from Cloudinary (cocktailDB/ in the doa0oeo13 account), copied from
-- TheCocktailDB by scripts/upload-images-cloudinary.mjs. Attribution to TheCocktailDB stays.
-- Only rows that differ change, so re-running it is harmless.
UPDATE "drinks"
SET "image" = 'https://res.cloudinary.com/doa0oeo13/image/upload/cocktailDB/drinks/' || "id"
WHERE "image" LIKE 'https://www.thecocktaildb.com/%';
--> statement-breakpoint
WITH "ingredient_images" ("name", "image") AS (VALUES
  ('151 proof rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/151-proof-rum'),
  ('7-up', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/7-up'),
  ('7-Up', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/7-up'),
  ('Absinthe', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/absinthe'),
  ('Absolut Citron', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/absolut-citron'),
  ('Absolut Kurant', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/absolut-kurant'),
  ('Absolut Peppar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/absolut-peppar'),
  ('Absolut Vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/absolut-vodka'),
  ('Advocaat', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/advocaat'),
  ('Agave Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/agave-syrup'),
  ('Allspice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/allspice'),
  ('Almond flavoring', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/almond-flavoring'),
  ('Amaretto', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/amaretto'),
  ('Amaro Montenegro', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/amaro-montenegro'),
  ('Angostura bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/angostura-bitters'),
  ('Angostura Bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/angostura-bitters'),
  ('Anis', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/anis'),
  ('Anisette', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/anisette'),
  ('Añejo rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/anejo-rum'),
  ('Aperol', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/aperol'),
  ('Apfelkorn', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apfelkorn'),
  ('Apple', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apple'),
  ('Apple brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apple-brandy'),
  ('Apple Brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apple-brandy'),
  ('Apple juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apple-juice'),
  ('Applejack', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/applejack'),
  ('Apricot brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apricot-brandy'),
  ('Apricot Brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apricot-brandy'),
  ('Apricot Nectar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/apricot-nectar'),
  ('Asafoetida', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/asafoetida'),
  ('Bacardi Limon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/bacardi-limon'),
  ('Baileys irish cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/baileys-irish-cream'),
  ('Banana', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/banana'),
  ('Banana liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/banana-liqueur'),
  ('Beer', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/beer'),
  ('Benedictine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/benedictine'),
  ('Bitter lemon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/bitter-lemon'),
  ('Bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/bitters'),
  ('Black pepper', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/black-pepper'),
  ('Black Sambuca', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/black-sambuca'),
  ('Blackberries', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blackberries'),
  ('Blackberry brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blackberry-brandy'),
  ('Blackcurrant cordial', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blackcurrant-cordial'),
  ('blackstrap rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blackstrap-rum'),
  ('Blended Scotch', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blended-scotch'),
  ('Blended whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blended-whiskey'),
  ('Blood Orange', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blood-orange'),
  ('Blue Curacao', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blue-curacao'),
  ('Blueberry schnapps', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/blueberry-schnapps'),
  ('Bourbon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/bourbon'),
  ('Brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/brandy'),
  ('Brown sugar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/brown-sugar'),
  ('Butter', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/butter'),
  ('Butterscotch schnapps', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/butterscotch-schnapps'),
  ('Cachaca', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cachaca'),
  ('Campari', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/campari'),
  ('Caramel coloring', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/caramel-coloring'),
  ('Carbonated soft drink', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/carbonated-soft-drink'),
  ('Carbonated water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/carbonated-water'),
  ('Cardamom', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cardamom'),
  ('Cayenne pepper', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cayenne-pepper'),
  ('Celery salt', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/celery-salt'),
  ('Chambord raspberry liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/chambord-raspberry-liqueur'),
  ('Champagne', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/champagne'),
  ('Cherries', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherries'),
  ('Cherry', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherry'),
  ('Cherry brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherry-brandy'),
  ('Cherry Heering', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherry-heering'),
  ('Cherry Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherry-juice'),
  ('Cherry liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cherry-liqueur'),
  ('Chocolate', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/chocolate'),
  ('Chocolate liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/chocolate-liqueur'),
  ('Chocolate syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/chocolate-syrup'),
  ('Cider', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cider'),
  ('Cinnamon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cinnamon'),
  ('Cloves', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cloves'),
  ('Club soda', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/club-soda'),
  ('Coca-Cola', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coca-cola'),
  ('Cocoa powder', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cocoa-powder'),
  ('Coconut liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coconut-liqueur'),
  ('Coconut Liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coconut-liqueur'),
  ('Coconut milk', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coconut-milk'),
  ('Coconut syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coconut-syrup'),
  ('Coffee', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coffee'),
  ('Coffee brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coffee-brandy'),
  ('Coffee liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coffee-liqueur'),
  ('Cognac', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cognac'),
  ('Cointreau', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cointreau'),
  ('Condensed milk', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/condensed-milk'),
  ('Coriander', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/coriander'),
  ('Corn syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/corn-syrup'),
  ('Corona', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/corona'),
  ('Cranberry juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cranberry-juice'),
  ('Cranberry Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cranberry-juice'),
  ('Cranberry vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cranberry-vodka'),
  ('Cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cream'),
  ('Cream of coconut', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cream-of-coconut'),
  ('Creme de Banane', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/creme-de-banane'),
  ('Creme De Banane', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/creme-de-banane'),
  ('Creme de Cacao', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/creme-de-cacao'),
  ('Creme de Cassis', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/creme-de-cassis'),
  ('Creme de Mure', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/creme-de-mure'),
  ('Crown Royal', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/crown-royal'),
  ('Cucumber', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cucumber'),
  ('Cumin seed', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/cumin-seed'),
  ('Daiquiri mix', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/daiquiri-mix'),
  ('Dark Creme de Cacao', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dark-creme-de-cacao'),
  ('Dark rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dark-rum'),
  ('Dark Rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dark-rum'),
  ('demerara Sugar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/demerara-sugar'),
  ('Dr. Pepper', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dr-pepper'),
  ('Drambuie', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/drambuie'),
  ('Dry Vermouth', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dry-vermouth'),
  ('Dubonnet Rouge', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/dubonnet-rouge'),
  ('Egg', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/egg'),
  ('Egg white', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/egg-white'),
  ('Egg White', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/egg-white'),
  ('Egg yolk', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/egg-yolk'),
  ('Egg Yolk', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/egg-yolk'),
  ('Elderflower cordial', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/elderflower-cordial'),
  ('Espresso', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/espresso'),
  ('Everclear', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/everclear'),
  ('Falernum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/falernum'),
  ('Figs', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/figs'),
  ('Firewater', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/firewater'),
  ('Frangelico', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/frangelico'),
  ('Fresca', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fresca'),
  ('Fresh Lemon Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fresh-lemon-juice'),
  ('Fresh Lime Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fresh-lime-juice'),
  ('Fruit', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fruit'),
  ('Fruit juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fruit-juice'),
  ('Fruit punch', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/fruit-punch'),
  ('Galliano', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/galliano'),
  ('gin', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/gin'),
  ('Gin', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/gin'),
  ('Ginger', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ginger'),
  ('Ginger ale', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ginger-ale'),
  ('Ginger Beer', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ginger-beer'),
  ('Ginger Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ginger-syrup'),
  ('Godiva liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/godiva-liqueur'),
  ('Gold rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/gold-rum'),
  ('Goldschlager', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/goldschlager'),
  ('Grain alcohol', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grain-alcohol'),
  ('Grand Marnier', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grand-marnier'),
  ('Grape juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grape-juice'),
  ('Grape Soda', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grape-soda'),
  ('Grapefruit juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grapefruit-juice'),
  ('Grapefruit Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grapefruit-juice'),
  ('Green Chartreuse', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/green-chartreuse'),
  ('Green Creme de Menthe', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/green-creme-de-menthe'),
  ('Grenadine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/grenadine'),
  ('Guinness stout', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/guinness-stout'),
  ('Half-and-half', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/half-and-half'),
  ('Heavy cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/heavy-cream'),
  ('Honey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/honey'),
  ('Honey syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/honey-syrup'),
  ('Hot Chocolate', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/hot-chocolate'),
  ('Hot Damn', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/hot-damn'),
  ('Hot Sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/hot-sauce'),
  ('Ice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ice'),
  ('Iced tea', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/iced-tea'),
  ('Irish cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/irish-cream'),
  ('Irish whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/irish-whiskey'),
  ('Irish Whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/irish-whiskey'),
  ('Islay single malt Scotch', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/islay-single-malt-scotch'),
  ('Jack Daniels', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/jack-daniels'),
  ('Jagermeister', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/jagermeister'),
  ('Jägermeister', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/jagermeister'),
  ('Jello', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/jello'),
  ('Jim Beam', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/jim-beam'),
  ('Johnnie Walker', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/johnnie-walker'),
  ('Kahlua', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/kahlua'),
  ('Kiwi', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/kiwi'),
  ('Kiwi liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/kiwi-liqueur'),
  ('Kool-Aid', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/kool-aid'),
  ('Lager', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lager'),
  ('Lavender', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lavender'),
  ('lemon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon'),
  ('Lemon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon'),
  ('lemon juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-juice'),
  ('Lemon juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-juice'),
  ('Lemon Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-juice'),
  ('Lemon peel', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-peel'),
  ('Lemon Peel', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-peel'),
  ('Lemon-lime soda', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemon-lime-soda'),
  ('Lemonade', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lemonade'),
  ('Light cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/light-cream'),
  ('Light rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/light-rum'),
  ('Lillet', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lillet'),
  ('Lillet Blanc', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lillet-blanc'),
  ('Lime', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lime'),
  ('Lime juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lime-juice'),
  ('Lime Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lime-juice'),
  ('Lime peel', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lime-peel'),
  ('Lime vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/lime-vodka'),
  ('Limeade', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/limeade'),
  ('Malibu rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/malibu-rum'),
  ('Mango', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/mango'),
  ('Maple syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maple-syrup'),
  ('Maraschino cherry', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maraschino-cherry'),
  ('Maraschino Cherry', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maraschino-cherry'),
  ('maraschino liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maraschino-liqueur'),
  ('Maraschino liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maraschino-liqueur'),
  ('Maraschino Liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/maraschino-liqueur'),
  ('Marshmallows', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/marshmallows'),
  ('Melon Liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/melon-liqueur'),
  ('Mezcal', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/mezcal'),
  ('Midori melon liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/midori-melon-liqueur'),
  ('Milk', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/milk'),
  ('Mint', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/mint'),
  ('Mint syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/mint-syrup'),
  ('Mountain Dew', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/mountain-dew'),
  ('Nutmeg', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/nutmeg'),
  ('Olive', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/olive'),
  ('Olive Brine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/olive-brine'),
  ('Orange', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange'),
  ('Orange bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-bitters'),
  ('Orange Bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-bitters'),
  ('Orange Curacao', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-curacao'),
  ('Orange juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-juice'),
  ('Orange Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-juice'),
  ('Orange peel', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-peel'),
  ('Orange Peel', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-peel'),
  ('Orange spiral', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orange-spiral'),
  ('Oreo cookie', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/oreo-cookie'),
  ('Orgeat syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orgeat-syrup'),
  ('Orgeat Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/orgeat-syrup'),
  ('Ouzo', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ouzo'),
  ('Papaya', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/papaya'),
  ('Passion fruit juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/passion-fruit-juice'),
  ('Passion fruit syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/passion-fruit-syrup'),
  ('Passoa', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/passoa'),
  ('Peach Bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peach-bitters'),
  ('Peach brandy', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peach-brandy'),
  ('Peach nectar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peach-nectar'),
  ('Peach schnapps', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peach-schnapps'),
  ('Peach Vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peach-vodka'),
  ('Peachtree schnapps', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peachtree-schnapps'),
  ('Pepper', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pepper'),
  ('Pepsi Cola', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pepsi-cola'),
  ('Pernod', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pernod'),
  ('Peychaud bitters', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/peychaud-bitters'),
  ('Pina colada mix', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pina-colada-mix'),
  ('Pineapple', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pineapple'),
  ('pineapple juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pineapple-juice'),
  ('Pineapple juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pineapple-juice'),
  ('Pineapple Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pineapple-juice'),
  ('Pineapple Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pineapple-syrup'),
  ('Pink lemonade', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pink-lemonade'),
  ('Pisang Ambon', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pisang-ambon'),
  ('Pisco', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pisco'),
  ('Pomegranate juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/pomegranate-juice'),
  ('Port', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/port'),
  ('Powdered sugar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/powdered-sugar'),
  ('Prosecco', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/prosecco'),
  ('Raspberry Liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/raspberry-liqueur'),
  ('Raspberry syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/raspberry-syrup'),
  ('Raspberry vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/raspberry-vodka'),
  ('Red Chili Flakes', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/red-chili-flakes'),
  ('Red wine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/red-wine'),
  ('Ricard', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ricard'),
  ('Root beer', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/root-beer'),
  ('Rose', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rose'),
  ('Rosemary', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rosemary'),
  ('Rosemary Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rosemary-syrup'),
  ('Roses sweetened lime juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/roses-sweetened-lime-juice'),
  ('Rosso Vermouth', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rosso-vermouth'),
  ('Ruby Port', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/ruby-port'),
  ('Rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rum'),
  ('Rumple Minze', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rumple-minze'),
  ('Rye whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rye-whiskey'),
  ('Rye Whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/rye-whiskey'),
  ('Salt', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/salt'),
  ('Sambuca', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sambuca'),
  ('Sarsaparilla', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sarsaparilla'),
  ('Schweppes Russchian', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/schweppes-russchian'),
  ('Scotch', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/scotch'),
  ('Sherbet', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sherbet'),
  ('Sherry', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sherry'),
  ('Sirup of roses', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sirup-of-roses'),
  ('Sloe gin', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sloe-gin'),
  ('Soda water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/soda-water'),
  ('Soda Water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/soda-water'),
  ('Sour mix', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sour-mix'),
  ('Southern Comfort', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/southern-comfort'),
  ('Soy Sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/soy-sauce'),
  ('Spiced rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/spiced-rum'),
  ('Sprite', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sprite'),
  ('St. Germain', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/st-germain'),
  ('Strawberries', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/strawberries'),
  ('Strawberry liqueur', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/strawberry-liqueur'),
  ('Strawberry schnapps', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/strawberry-schnapps'),
  ('Sugar', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sugar'),
  ('Sugar syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sugar-syrup'),
  ('Sugar Syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sugar-syrup'),
  ('Surge', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/surge'),
  ('Sweet and sour', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sweet-and-sour'),
  ('Sweet and Sour', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sweet-and-sour'),
  ('Sweet Vermouth', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/sweet-vermouth'),
  ('Tabasco sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tabasco-sauce'),
  ('Tabasco Sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tabasco-sauce'),
  ('Tea', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tea'),
  ('Tennessee whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tennessee-whiskey'),
  ('Tequila', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tequila'),
  ('Thyme', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/thyme'),
  ('Tia maria', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tia-maria'),
  ('Tomato juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tomato-juice'),
  ('Tomato Juice', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tomato-juice'),
  ('Tonic water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tonic-water'),
  ('Tonic Water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/tonic-water'),
  ('Triple sec', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/triple-sec'),
  ('Triple Sec', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/triple-sec'),
  ('Vanilla', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vanilla'),
  ('Vanilla extract', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vanilla-extract'),
  ('Vanilla ice-cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vanilla-ice-cream'),
  ('Vanilla syrup', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vanilla-syrup'),
  ('Vanilla vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vanilla-vodka'),
  ('Vermouth', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vermouth'),
  ('Vodka', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/vodka'),
  ('Water', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/water'),
  ('Whipped cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/whipped-cream'),
  ('Whipping cream', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/whipping-cream'),
  ('Whiskey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/whiskey'),
  ('Whisky', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/whisky'),
  ('White Creme de Menthe', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/white-creme-de-menthe'),
  ('White rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/white-rum'),
  ('White Rum', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/white-rum'),
  ('White Wine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/white-wine'),
  ('Wild Turkey', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/wild-turkey'),
  ('Wine', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/wine'),
  ('Worcestershire sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/worcestershire-sauce'),
  ('Worcestershire Sauce', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/worcestershire-sauce'),
  ('Wormwood', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/wormwood'),
  ('Yellow Chartreuse', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/yellow-chartreuse'),
  ('Yoghurt', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/yoghurt'),
  ('Yukon Jack', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/yukon-jack'),
  ('Zima', 'https://res.cloudinary.com/doa0oeo13/image/upload/c_fit,w_100,h_100,f_auto,q_auto/cocktailDB/ingredients/zima')
)
UPDATE "drinks" AS d
SET "ingredients" = (
  SELECT jsonb_agg(
    CASE WHEN m."name" IS NULL THEN e.item
    ELSE jsonb_set(e.item, '{image}', coalesce(to_jsonb(m."image"), 'null'::jsonb)) END
    ORDER BY e.position)
  FROM jsonb_array_elements(d."ingredients") WITH ORDINALITY AS e(item, position)
  LEFT JOIN "ingredient_images" m ON m."name" = e.item->>'name'
)
WHERE EXISTS (
  SELECT 1 FROM jsonb_array_elements(d."ingredients") AS e(item)
  JOIN "ingredient_images" m ON m."name" = e.item->>'name'
  WHERE e.item->>'image' IS DISTINCT FROM m."image"
);
