/** Non-secret values so the app boots in tests. Real adapters are replaced by fakes. */
export const TEST_ENV: Record<string, string> = {
  NODE_ENV: 'test',
  PORT: '0',
  TRUST_PROXY: 'false',
  OPENAPI_ENABLED: 'true',
  COCKTAILDB_BASE_URL: 'http://cocktaildb.test/api/json/v1',
  COCKTAILDB_API_KEY: 'test',
  COCKTAILDB_TIMEOUT_MS: '1000',
  COCKTAILDB_RETRIES: '0',
  COCKTAILDB_CRAWL_CONCURRENCY: '1',
  CATALOG_TTL_MS: '60000',
  DB_HOST: 'db.test',
  DB_PORT: '5432',
  DB_NAME: 'test',
  DB_USER: 'test',
  DB_PASSWORD: 'test',
  DB_POOL_MAX: '1',
  JWT_SECRET: 'test-secret-that-is-at-least-32-characters-long',
  JWT_ACCESS_TTL_SECONDS: '900',
  REFRESH_TOKEN_TTL_DAYS: '30',
  LOGIN_MAX_FAILURES_PER_ACCOUNT: '3',
  LOGIN_MAX_FAILURES_PER_IP: '50',
  LOGIN_LOCKOUT_WINDOW_SECONDS: '900',
  ADMIN_EMAIL: 'admin@test.local',
  ADMIN_PASSWORD: 'admin-password-123',
  ADMIN_NAME: 'Admin',
  ADMIN_BIRTH_DATE: '1990-01-01',
};
