import { Logger } from '@nestjs/common';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';
import { loadEnvFile, parseDatabaseEnv } from '../config/env.js';

/** Folder with the SQL migrations generated by drizzle-kit (copied into the Docker image). */
const MIGRATIONS_FOLDER = 'drizzle';

/**
 * Applies pending migrations without drizzle-kit (a dev dependency), so the production
 * image can migrate: `node dist/shared/infrastructure/database/migrate.js`.
 */
async function main(): Promise<void> {
  loadEnvFile();
  const env = parseDatabaseEnv();
  const pool = new Pool({
    host: env.DB_HOST,
    port: env.DB_PORT,
    database: env.DB_NAME,
    user: env.DB_USER,
    password: env.DB_PASSWORD,
    max: 1,
  });
  try {
    await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS_FOLDER });
    Logger.log('Migrations applied', 'Migrate');
  } finally {
    await pool.end();
  }
}

await main();
