import { Logger } from '@nestjs/common';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';
import type { DatabaseEnv } from '../config/env.js';

/** Folder with the SQL migrations generated by drizzle-kit (copied into the Docker image). */
const MIGRATIONS_FOLDER = 'drizzle';
/** Any constant: identifies this app's migration lock in pg_locks. */
const MIGRATION_LOCK_ID = 872_431_965;

/**
 * Applies pending migrations without drizzle-kit (a dev dependency). Holds a Postgres advisory
 * lock meanwhile: when several replicas start at once, one migrates and the rest wait.
 */
export async function runMigrations(env: DatabaseEnv): Promise<void> {
  const pool = new Pool({
    host: env.DB_HOST,
    port: env.DB_PORT,
    database: env.DB_NAME,
    user: env.DB_USER,
    password: env.DB_PASSWORD,
    max: 1,
  });
  const client = await pool.connect();
  try {
    await client.query('select pg_advisory_lock($1)', [MIGRATION_LOCK_ID]);
    await migrate(drizzle(client), { migrationsFolder: MIGRATIONS_FOLDER });
    Logger.log('Migrations applied', 'Migrate');
  } finally {
    await client
      .query('select pg_advisory_unlock($1)', [MIGRATION_LOCK_ID])
      .catch(() => undefined);
    client.release();
    await pool.end();
  }
}
